#NextCloud+MariaDB+Redis
#Kamil Kobak
version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    container_name: mariadb          
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=jakieshasloroota
      - MYSQL_PASSWORD=jakieshaslousera
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - TZ=Europe/Warsaw

  redis:
    image: redis:alpine
    restart: always

  nextcloud:
    container_name: nextcloud          
    restart: unless-stopped
    image: nextcloud
    environment:
      - MYSQL_HOST=mariadb
      - REDIS_HOST=redis    
    ports:
      - 80:80
      - 443:443
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    depends_on:
      - db
      - redis

